# _plugins/image_alt_injector.rb
#
# Post-render hook that injects alt attributes into <img> tags using
# descriptions from _data/image_alt.json (generated by describe_images.py).
#
# Matches images by their src path. If an image already has a non-empty alt,
# it is left untouched. Only adds alt when missing or empty.

require 'json'

Jekyll::Hooks.register [:pages, :documents], :post_render do |doc|
  next unless doc.output_ext == '.html'

  site = doc.site
  alt_data = site.data['image_alt']
  next if alt_data.nil? || alt_data.empty?

  # Match <img> tags with missing alt or empty alt=""
  doc.output = doc.output.gsub(/<img\s([^>]*)>/i) do |tag|
    attrs = $1

    # Skip if already has a meaningful alt attribute
    if attrs =~ /\balt\s*=\s*["']([^"']*)["']/i
      next tag if $1.strip != ''
      # Has alt="" — we'll replace it
      has_empty_alt = true
    else
      has_empty_alt = false
    end

    # Extract src
    next tag unless attrs =~ /\bsrc\s*=\s*["']([^"']*)["']/i
    src = $1

    # Normalize src to a root-relative path for lookup
    # Strip query strings and fragments
    src_path = src.split('?').first.split('#').first
    # Make root-relative if it isn't already
    src_path = '/' + src_path unless src_path.start_with?('/')

    description = alt_data[src_path]
    next tag if description.nil? || description.strip.empty?

    escaped = description.gsub('"', '&quot;')

    if has_empty_alt
      # Replace existing empty alt
      tag.gsub(/\balt\s*=\s*["'][^"']*["']/i, "alt=\"#{escaped}\"")
    else
      # Inject alt before the closing >
      "<img #{attrs} alt=\"#{escaped}\">"
    end
  end
end
