name: Build Page
on:
  push:
    branches:
      - 'master'
jobs:
  build_page:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: racerxdl/letshackit:latest